name: Kubernetes Deployment

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

# You need to Base64 encoded your kubeconfig file before adding it in github sercrets
    - name: Setup Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig

    - name: Apply Kubernetes configurations
      run: |
        export KUBECONFIG=kubeconfig
        kubectl apply -n go-survey -f k8s/
